#!/usr/bin/bash



if [ ! -f UnicodeData-14.0.0.txt ] ; then
    wget https://www.unicode.org/Public/13.0.0/ucd/UnicodeData.txt
    mv UnicodeData.txt UnicodeData-14.0.0.txt
fi
if [ ! -f Blocks-14.0.0.txt ] ; then
    wget https://www.unicode.org/Public/14.0.0/ucd/Blocks.txt
    mv Blocks.txt Blocks-14.0.0.txt
fi

if [ ! -f MathClass-15.txt ] ; then
    wget http://www.unicode.org/Public/math/revision-15/MathClass-15.txt
fi


   

TEMPLATE=${1-main}
echo "--- $TEMPLATE ---"

SAXON="java -jar saxon9he.jar "

$SAXON -it:$TEMPLATE unicodedata.xsl

# $SAXON -it:main unicodedata.xsl
# $SAXON -it:mathclass unicodedata.xsl
# $SAXON -it:unicode-math unicodedata.xsl
# $SAXON -it:opdict unicodedata.xsl

if [ $? != 0 ] ; then
  echo XSLT error
  exit
fi


# put long attributes back on same line
sed  -i ':a;N;$!ba;s/"\n */" /g' uc-new.xml 

echo diff
diff -c unicode.xml uc-new.xml
