#!/usr/bin/bash

SAXON="java -jar saxon9he.jar "

$SAXON character-set.xml characters-restyle.xsl glyphs=glyphs  editors-copy=yes 
cp -r index.html 2007doc restyle

$SAXON character-set.xml characters.xsl glyphs=glyphs  editors-copy=yes 
$SAXON unicode.xml charmap.xsl
$SAXON unicode.xml entities.xsl
$SAXON unicode.xml unicode-names.xsl > unicode-names.js
exit
