
<!--
     File mmlaliasmap.xsl  produced by the XSL script charmap.xsl
     from input data in unicode.xml.

     Copyright 2003 - 2013 W3C.

     Use and distribution of this code are permitted under the terms of the
     W3C Software Notice and License.
     http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html

     Please report any errors to David Carlisle
     via the public W3C list www-math@w3.org.

     The numeric character values assigned to each entity
     (should) match the Unicode assignments in Unicode 5.2.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
<xsl:character-map name="mmlalias">
  <xsl:output-character character="&#x2220;" string="&amp;angle;"/>
  <xsl:output-character character="&#x2061;" string="&amp;ApplyFunction;"/>
  <xsl:output-character character="&#x2248;" string="&amp;approx;"/>
  <xsl:output-character character="&#x224a;" string="&amp;approxeq;"/>
  <xsl:output-character character="&#x2254;" string="&amp;Assign;"/>
  <xsl:output-character character="&#x224c;" string="&amp;backcong;"/>
  <xsl:output-character character="&#x3f6;" string="&amp;backepsilon;"/>
  <xsl:output-character character="&#x2035;" string="&amp;backprime;"/>
  <xsl:output-character character="&#x223d;" string="&amp;backsim;"/>
  <xsl:output-character character="&#x22cd;" string="&amp;backsimeq;"/>
  <xsl:output-character character="&#x2216;" string="&amp;Backslash;"/>
  <xsl:output-character character="&#x2305;" string="&amp;barwedge;"/>
  <xsl:output-character character="&#x2235;" string="&amp;because;"/>
  <xsl:output-character character="&#x2235;" string="&amp;Because;"/>
  <xsl:output-character character="&#x212c;" string="&amp;Bernoullis;"/>
  <xsl:output-character character="&#x226c;" string="&amp;between;"/>
  <xsl:output-character character="&#x22c2;" string="&amp;bigcap;"/>
  <xsl:output-character character="&#x25ef;" string="&amp;bigcirc;"/>
  <xsl:output-character character="&#x22c3;" string="&amp;bigcup;"/>
  <xsl:output-character character="&#x2a00;" string="&amp;bigodot;"/>
  <xsl:output-character character="&#x2a01;" string="&amp;bigoplus;"/>
  <xsl:output-character character="&#x2a02;" string="&amp;bigotimes;"/>
  <xsl:output-character character="&#x2a06;" string="&amp;bigsqcup;"/>
  <xsl:output-character character="&#x2605;" string="&amp;bigstar;"/>
  <xsl:output-character character="&#x25bd;" string="&amp;bigtriangledown;"/>
  <xsl:output-character character="&#x25b3;" string="&amp;bigtriangleup;"/>
  <xsl:output-character character="&#x2a04;" string="&amp;biguplus;"/>
  <xsl:output-character character="&#x22c1;" string="&amp;bigvee;"/>
  <xsl:output-character character="&#x22c0;" string="&amp;bigwedge;"/>
  <xsl:output-character character="&#x290d;" string="&amp;bkarow;"/>
  <xsl:output-character character="&#x29eb;" string="&amp;blacklozenge;"/>
  <xsl:output-character character="&#x25aa;" string="&amp;blacksquare;"/>
  <xsl:output-character character="&#x25b4;" string="&amp;blacktriangle;"/>
  <xsl:output-character character="&#x25be;" string="&amp;blacktriangledown;"/>
  <xsl:output-character character="&#x25c2;" string="&amp;blacktriangleleft;"/>
  <xsl:output-character character="&#x25b8;" string="&amp;blacktriangleright;"/>
  <xsl:output-character character="&#x22a5;" string="&amp;bot;"/>
  <xsl:output-character character="&#x229f;" string="&amp;boxminus;"/>
  <xsl:output-character character="&#x229e;" string="&amp;boxplus;"/>
  <xsl:output-character character="&#x22a0;" string="&amp;boxtimes;"/>
  <xsl:output-character character="&#x2d8;" string="&amp;Breve;"/>
  <xsl:output-character character="&#x2022;" string="&amp;bullet;"/>
  <xsl:output-character character="&#x224f;" string="&amp;bumpeq;"/>
  <xsl:output-character character="&#x224e;" string="&amp;Bumpeq;"/>
  <xsl:output-character character="&#x2145;" string="&amp;CapitalDifferentialD;"/>
  <xsl:output-character character="&#x212d;" string="&amp;Cayleys;"/>
  <xsl:output-character character="&#xb8;" string="&amp;Cedilla;"/>
  <xsl:output-character character="&#xb7;" string="&amp;centerdot;"/>
  <xsl:output-character character="&#xb7;" string="&amp;CenterDot;"/>
  <xsl:output-character character="&#x2713;" string="&amp;checkmark;"/>
  <xsl:output-character character="&#x2257;" string="&amp;circeq;"/>
  <xsl:output-character character="&#x21ba;" string="&amp;circlearrowleft;"/>
  <xsl:output-character character="&#x21bb;" string="&amp;circlearrowright;"/>
  <xsl:output-character character="&#x229b;" string="&amp;circledast;"/>
  <xsl:output-character character="&#x229a;" string="&amp;circledcirc;"/>
  <xsl:output-character character="&#x229d;" string="&amp;circleddash;"/>
  <xsl:output-character character="&#x2299;" string="&amp;CircleDot;"/>
  <xsl:output-character character="&#xae;" string="&amp;circledR;"/>
  <xsl:output-character character="&#x24c8;" string="&amp;circledS;"/>
  <xsl:output-character character="&#x2296;" string="&amp;CircleMinus;"/>
  <xsl:output-character character="&#x2295;" string="&amp;CirclePlus;"/>
  <xsl:output-character character="&#x2297;" string="&amp;CircleTimes;"/>
  <xsl:output-character character="&#x2232;" string="&amp;ClockwiseContourIntegral;"/>
  <xsl:output-character character="&#x201d;" string="&amp;CloseCurlyDoubleQuote;"/>
  <xsl:output-character character="&#x2019;" string="&amp;CloseCurlyQuote;"/>
  <xsl:output-character character="&#x2663;" string="&amp;clubsuit;"/>
  <xsl:output-character character="&#x2254;" string="&amp;coloneq;"/>
  <xsl:output-character character="&#x2201;" string="&amp;complement;"/>
  <xsl:output-character character="&#x2102;" string="&amp;complexes;"/>
  <xsl:output-character character="&#x2261;" string="&amp;Congruent;"/>
  <xsl:output-character character="&#x222e;" string="&amp;ContourIntegral;"/>
  <xsl:output-character character="&#x2210;" string="&amp;Coproduct;"/>
  <xsl:output-character character="&#x2233;" string="&amp;CounterClockwiseContourIntegral;"/>
  <xsl:output-character character="&#x224d;" string="&amp;CupCap;"/>
  <xsl:output-character character="&#x22de;" string="&amp;curlyeqprec;"/>
  <xsl:output-character character="&#x22df;" string="&amp;curlyeqsucc;"/>
  <xsl:output-character character="&#x22ce;" string="&amp;curlyvee;"/>
  <xsl:output-character character="&#x22cf;" string="&amp;curlywedge;"/>
  <xsl:output-character character="&#x21b6;" string="&amp;curvearrowleft;"/>
  <xsl:output-character character="&#x21b7;" string="&amp;curvearrowright;"/>
  <xsl:output-character character="&#x290f;" string="&amp;dbkarow;"/>
  <xsl:output-character character="&#x2021;" string="&amp;ddagger;"/>
  <xsl:output-character character="&#x2a77;" string="&amp;ddotseq;"/>
  <xsl:output-character character="&#x2207;" string="&amp;Del;"/>
  <xsl:output-character character="&#xb4;" string="&amp;DiacriticalAcute;"/>
  <xsl:output-character character="&#x2d9;" string="&amp;DiacriticalDot;"/>
  <xsl:output-character character="&#x2dd;" string="&amp;DiacriticalDoubleAcute;"/>
  <!--U00060 DiacriticalGrave-->
  <xsl:output-character character="&#x2dc;" string="&amp;DiacriticalTilde;"/>
  <xsl:output-character character="&#x22c4;" string="&amp;diamond;"/>
  <xsl:output-character character="&#x22c4;" string="&amp;Diamond;"/>
  <xsl:output-character character="&#x2666;" string="&amp;diamondsuit;"/>
  <xsl:output-character character="&#x2146;" string="&amp;DifferentialD;"/>
  <xsl:output-character character="&#x3dd;" string="&amp;digamma;"/>
  <xsl:output-character character="&#xf7;" string="&amp;div;"/>
  <xsl:output-character character="&#x22c7;" string="&amp;divideontimes;"/>
  <xsl:output-character character="&#x2250;" string="&amp;doteq;"/>
  <xsl:output-character character="&#x2251;" string="&amp;doteqdot;"/>
  <xsl:output-character character="&#x2250;" string="&amp;DotEqual;"/>
  <xsl:output-character character="&#x2238;" string="&amp;dotminus;"/>
  <xsl:output-character character="&#x2214;" string="&amp;dotplus;"/>
  <xsl:output-character character="&#x22a1;" string="&amp;dotsquare;"/>
  <xsl:output-character character="&#x2306;" string="&amp;doublebarwedge;"/>
  <xsl:output-character character="&#x222f;" string="&amp;DoubleContourIntegral;"/>
  <xsl:output-character character="&#xa8;" string="&amp;DoubleDot;"/>
  <xsl:output-character character="&#x21d3;" string="&amp;DoubleDownArrow;"/>
  <xsl:output-character character="&#x21d0;" string="&amp;DoubleLeftArrow;"/>
  <xsl:output-character character="&#x21d4;" string="&amp;DoubleLeftRightArrow;"/>
  <xsl:output-character character="&#x2ae4;" string="&amp;DoubleLeftTee;"/>
  <xsl:output-character character="&#x27f8;" string="&amp;DoubleLongLeftArrow;"/>
  <xsl:output-character character="&#x27fa;" string="&amp;DoubleLongLeftRightArrow;"/>
  <xsl:output-character character="&#x27f9;" string="&amp;DoubleLongRightArrow;"/>
  <xsl:output-character character="&#x21d2;" string="&amp;DoubleRightArrow;"/>
  <xsl:output-character character="&#x22a8;" string="&amp;DoubleRightTee;"/>
  <xsl:output-character character="&#x21d1;" string="&amp;DoubleUpArrow;"/>
  <xsl:output-character character="&#x21d5;" string="&amp;DoubleUpDownArrow;"/>
  <xsl:output-character character="&#x2225;" string="&amp;DoubleVerticalBar;"/>
  <xsl:output-character character="&#x2193;" string="&amp;downarrow;"/>
  <xsl:output-character character="&#x21d3;" string="&amp;Downarrow;"/>
  <xsl:output-character character="&#x2193;" string="&amp;DownArrow;"/>
  <xsl:output-character character="&#x21f5;" string="&amp;DownArrowUpArrow;"/>
  <xsl:output-character character="&#x21ca;" string="&amp;downdownarrows;"/>
  <xsl:output-character character="&#x21c3;" string="&amp;downharpoonleft;"/>
  <xsl:output-character character="&#x21c2;" string="&amp;downharpoonright;"/>
  <xsl:output-character character="&#x21bd;" string="&amp;DownLeftVector;"/>
  <xsl:output-character character="&#x21c1;" string="&amp;DownRightVector;"/>
  <xsl:output-character character="&#x22a4;" string="&amp;DownTee;"/>
  <xsl:output-character character="&#x21a7;" string="&amp;DownTeeArrow;"/>
  <xsl:output-character character="&#x2910;" string="&amp;drbkarow;"/>
  <xsl:output-character character="&#x2208;" string="&amp;Element;"/>
  <xsl:output-character character="&#x2205;" string="&amp;emptyset;"/>
  <xsl:output-character character="&#x2256;" string="&amp;eqcirc;"/>
  <xsl:output-character character="&#x2255;" string="&amp;eqcolon;"/>
  <xsl:output-character character="&#x2242;" string="&amp;eqsim;"/>
  <xsl:output-character character="&#x2a96;" string="&amp;eqslantgtr;"/>
  <xsl:output-character character="&#x2a95;" string="&amp;eqslantless;"/>
  <xsl:output-character character="&#x2242;" string="&amp;EqualTilde;"/>
  <xsl:output-character character="&#x21cc;" string="&amp;Equilibrium;"/>
  <xsl:output-character character="&#x2203;" string="&amp;Exists;"/>
  <xsl:output-character character="&#x2130;" string="&amp;expectation;"/>
  <xsl:output-character character="&#x2147;" string="&amp;exponentiale;"/>
  <xsl:output-character character="&#x2147;" string="&amp;ExponentialE;"/>
  <xsl:output-character character="&#x2252;" string="&amp;fallingdotseq;"/>
  <xsl:output-character character="&#x2200;" string="&amp;ForAll;"/>
  <xsl:output-character character="&#x2131;" string="&amp;Fouriertrf;"/>
  <xsl:output-character character="&#x2265;" string="&amp;geq;"/>
  <xsl:output-character character="&#x2267;" string="&amp;geqq;"/>
  <xsl:output-character character="&#x2a7e;" string="&amp;geqslant;"/>
  <xsl:output-character character="&#x226b;" string="&amp;gg;"/>
  <xsl:output-character character="&#x22d9;" string="&amp;ggg;"/>
  <xsl:output-character character="&#x2a8a;" string="&amp;gnapprox;"/>
  <xsl:output-character character="&#x2a88;" string="&amp;gneq;"/>
  <xsl:output-character character="&#x2269;" string="&amp;gneqq;"/>
  <xsl:output-character character="&#x2265;" string="&amp;GreaterEqual;"/>
  <xsl:output-character character="&#x22db;" string="&amp;GreaterEqualLess;"/>
  <xsl:output-character character="&#x2267;" string="&amp;GreaterFullEqual;"/>
  <xsl:output-character character="&#x2277;" string="&amp;GreaterLess;"/>
  <xsl:output-character character="&#x2a7e;" string="&amp;GreaterSlantEqual;"/>
  <xsl:output-character character="&#x2273;" string="&amp;GreaterTilde;"/>
  <xsl:output-character character="&#x2a86;" string="&amp;gtrapprox;"/>
  <xsl:output-character character="&#x22d7;" string="&amp;gtrdot;"/>
  <xsl:output-character character="&#x22db;" string="&amp;gtreqless;"/>
  <xsl:output-character character="&#x2a8c;" string="&amp;gtreqqless;"/>
  <xsl:output-character character="&#x2277;" string="&amp;gtrless;"/>
  <xsl:output-character character="&#x2273;" string="&amp;gtrsim;"/>
  <!--U02269-0FE00 gvertneqq-->
  <xsl:output-character character="&#x2c7;" string="&amp;Hacek;"/>
  <xsl:output-character character="&#x210f;" string="&amp;hbar;"/>
  <xsl:output-character character="&#x2665;" string="&amp;heartsuit;"/>
  <xsl:output-character character="&#x210b;" string="&amp;HilbertSpace;"/>
  <xsl:output-character character="&#x2925;" string="&amp;hksearow;"/>
  <xsl:output-character character="&#x2926;" string="&amp;hkswarow;"/>
  <xsl:output-character character="&#x21a9;" string="&amp;hookleftarrow;"/>
  <xsl:output-character character="&#x21aa;" string="&amp;hookrightarrow;"/>
  <xsl:output-character character="&#x210f;" string="&amp;hslash;"/>
  <xsl:output-character character="&#x224e;" string="&amp;HumpDownHump;"/>
  <xsl:output-character character="&#x224f;" string="&amp;HumpEqual;"/>
  <xsl:output-character character="&#x2a0c;" string="&amp;iiiint;"/>
  <xsl:output-character character="&#x222d;" string="&amp;iiint;"/>
  <xsl:output-character character="&#x2111;" string="&amp;Im;"/>
  <xsl:output-character character="&#x2148;" string="&amp;ImaginaryI;"/>
  <xsl:output-character character="&#x2110;" string="&amp;imagline;"/>
  <xsl:output-character character="&#x2111;" string="&amp;imagpart;"/>
  <xsl:output-character character="&#x21d2;" string="&amp;Implies;"/>
  <xsl:output-character character="&#x2208;" string="&amp;in;"/>
  <xsl:output-character character="&#x2124;" string="&amp;integers;"/>
  <xsl:output-character character="&#x222b;" string="&amp;Integral;"/>
  <xsl:output-character character="&#x22ba;" string="&amp;intercal;"/>
  <xsl:output-character character="&#x22c2;" string="&amp;Intersection;"/>
  <xsl:output-character character="&#x2a3c;" string="&amp;intprod;"/>
  <xsl:output-character character="&#x2063;" string="&amp;InvisibleComma;"/>
  <xsl:output-character character="&#x2062;" string="&amp;InvisibleTimes;"/>
  <xsl:output-character character="&#x27e8;" string="&amp;langle;"/>
  <xsl:output-character character="&#x2112;" string="&amp;Laplacetrf;"/>
  <!--U0007B lbrace-->
  <!--U0005B lbrack-->
  <xsl:output-character character="&#x27e8;" string="&amp;LeftAngleBracket;"/>
  <xsl:output-character character="&#x2190;" string="&amp;leftarrow;"/>
  <xsl:output-character character="&#x21d0;" string="&amp;Leftarrow;"/>
  <xsl:output-character character="&#x2190;" string="&amp;LeftArrow;"/>
  <xsl:output-character character="&#x21e4;" string="&amp;LeftArrowBar;"/>
  <xsl:output-character character="&#x21c6;" string="&amp;LeftArrowRightArrow;"/>
  <xsl:output-character character="&#x21a2;" string="&amp;leftarrowtail;"/>
  <xsl:output-character character="&#x2308;" string="&amp;LeftCeiling;"/>
  <xsl:output-character character="&#x27e6;" string="&amp;LeftDoubleBracket;"/>
  <xsl:output-character character="&#x21c3;" string="&amp;LeftDownVector;"/>
  <xsl:output-character character="&#x230a;" string="&amp;LeftFloor;"/>
  <xsl:output-character character="&#x21bd;" string="&amp;leftharpoondown;"/>
  <xsl:output-character character="&#x21bc;" string="&amp;leftharpoonup;"/>
  <xsl:output-character character="&#x21c7;" string="&amp;leftleftarrows;"/>
  <xsl:output-character character="&#x2194;" string="&amp;leftrightarrow;"/>
  <xsl:output-character character="&#x21d4;" string="&amp;Leftrightarrow;"/>
  <xsl:output-character character="&#x2194;" string="&amp;LeftRightArrow;"/>
  <xsl:output-character character="&#x21c6;" string="&amp;leftrightarrows;"/>
  <xsl:output-character character="&#x21cb;" string="&amp;leftrightharpoons;"/>
  <xsl:output-character character="&#x21ad;" string="&amp;leftrightsquigarrow;"/>
  <xsl:output-character character="&#x22a3;" string="&amp;LeftTee;"/>
  <xsl:output-character character="&#x21a4;" string="&amp;LeftTeeArrow;"/>
  <xsl:output-character character="&#x22cb;" string="&amp;leftthreetimes;"/>
  <xsl:output-character character="&#x22b2;" string="&amp;LeftTriangle;"/>
  <xsl:output-character character="&#x22b4;" string="&amp;LeftTriangleEqual;"/>
  <xsl:output-character character="&#x21bf;" string="&amp;LeftUpVector;"/>
  <xsl:output-character character="&#x21bc;" string="&amp;LeftVector;"/>
  <xsl:output-character character="&#x2264;" string="&amp;leq;"/>
  <xsl:output-character character="&#x2266;" string="&amp;leqq;"/>
  <xsl:output-character character="&#x2a7d;" string="&amp;leqslant;"/>
  <xsl:output-character character="&#x2a85;" string="&amp;lessapprox;"/>
  <xsl:output-character character="&#x22d6;" string="&amp;lessdot;"/>
  <xsl:output-character character="&#x22da;" string="&amp;lesseqgtr;"/>
  <xsl:output-character character="&#x2a8b;" string="&amp;lesseqqgtr;"/>
  <xsl:output-character character="&#x22da;" string="&amp;LessEqualGreater;"/>
  <xsl:output-character character="&#x2266;" string="&amp;LessFullEqual;"/>
  <xsl:output-character character="&#x2276;" string="&amp;LessGreater;"/>
  <xsl:output-character character="&#x2276;" string="&amp;lessgtr;"/>
  <xsl:output-character character="&#x2272;" string="&amp;lesssim;"/>
  <xsl:output-character character="&#x2a7d;" string="&amp;LessSlantEqual;"/>
  <xsl:output-character character="&#x2272;" string="&amp;LessTilde;"/>
  <xsl:output-character character="&#x226a;" string="&amp;ll;"/>
  <xsl:output-character character="&#x231e;" string="&amp;llcorner;"/>
  <xsl:output-character character="&#x21da;" string="&amp;Lleftarrow;"/>
  <xsl:output-character character="&#x23b0;" string="&amp;lmoustache;"/>
  <xsl:output-character character="&#x2a89;" string="&amp;lnapprox;"/>
  <xsl:output-character character="&#x2a87;" string="&amp;lneq;"/>
  <xsl:output-character character="&#x2268;" string="&amp;lneqq;"/>
  <xsl:output-character character="&#x27f5;" string="&amp;longleftarrow;"/>
  <xsl:output-character character="&#x27f8;" string="&amp;Longleftarrow;"/>
  <xsl:output-character character="&#x27f5;" string="&amp;LongLeftArrow;"/>
  <xsl:output-character character="&#x27f7;" string="&amp;longleftrightarrow;"/>
  <xsl:output-character character="&#x27fa;" string="&amp;Longleftrightarrow;"/>
  <xsl:output-character character="&#x27f7;" string="&amp;LongLeftRightArrow;"/>
  <xsl:output-character character="&#x27fc;" string="&amp;longmapsto;"/>
  <xsl:output-character character="&#x27f6;" string="&amp;longrightarrow;"/>
  <xsl:output-character character="&#x27f9;" string="&amp;Longrightarrow;"/>
  <xsl:output-character character="&#x27f6;" string="&amp;LongRightArrow;"/>
  <xsl:output-character character="&#x21ab;" string="&amp;looparrowleft;"/>
  <xsl:output-character character="&#x21ac;" string="&amp;looparrowright;"/>
  <xsl:output-character character="&#x2199;" string="&amp;LowerLeftArrow;"/>
  <xsl:output-character character="&#x2198;" string="&amp;LowerRightArrow;"/>
  <xsl:output-character character="&#x25ca;" string="&amp;lozenge;"/>
  <xsl:output-character character="&#x231f;" string="&amp;lrcorner;"/>
  <xsl:output-character character="&#x21b0;" string="&amp;Lsh;"/>
  <!--U02268-0FE00 lvertneqq-->
  <xsl:output-character character="&#x2720;" string="&amp;maltese;"/>
  <xsl:output-character character="&#x21a6;" string="&amp;mapsto;"/>
  <xsl:output-character character="&#x2221;" string="&amp;measuredangle;"/>
  <xsl:output-character character="&#x2133;" string="&amp;Mellintrf;"/>
  <xsl:output-character character="&#x2213;" string="&amp;MinusPlus;"/>
  <xsl:output-character character="&#x2213;" string="&amp;mp;"/>
  <xsl:output-character character="&#x22b8;" string="&amp;multimap;"/>
  <xsl:output-character character="&#x2249;" string="&amp;napprox;"/>
  <xsl:output-character character="&#x266e;" string="&amp;natural;"/>
  <xsl:output-character character="&#x2115;" string="&amp;naturals;"/>
  <xsl:output-character character="&#x2197;" string="&amp;nearrow;"/>
  <xsl:output-character character="&#x200b;" string="&amp;NegativeMediumSpace;"/>
  <xsl:output-character character="&#x200b;" string="&amp;NegativeThickSpace;"/>
  <xsl:output-character character="&#x200b;" string="&amp;NegativeThinSpace;"/>
  <xsl:output-character character="&#x200b;" string="&amp;NegativeVeryThinSpace;"/>
  <xsl:output-character character="&#x226b;" string="&amp;NestedGreaterGreater;"/>
  <xsl:output-character character="&#x226a;" string="&amp;NestedLessLess;"/>
  <xsl:output-character character="&#x2204;" string="&amp;nexists;"/>
  <xsl:output-character character="&#x2271;" string="&amp;ngeq;"/>
  <!--U02267-00338 ngeqq-->
  <!--U02A7E-00338 ngeqslant-->
  <xsl:output-character character="&#x226f;" string="&amp;ngtr;"/>
  <xsl:output-character character="&#x219a;" string="&amp;nleftarrow;"/>
  <xsl:output-character character="&#x21cd;" string="&amp;nLeftarrow;"/>
  <xsl:output-character character="&#x21ae;" string="&amp;nleftrightarrow;"/>
  <xsl:output-character character="&#x21ce;" string="&amp;nLeftrightarrow;"/>
  <xsl:output-character character="&#x2270;" string="&amp;nleq;"/>
  <!--U02266-00338 nleqq-->
  <!--U02A7D-00338 nleqslant-->
  <xsl:output-character character="&#x226e;" string="&amp;nless;"/>
  <xsl:output-character character="&#xa0;" string="&amp;NonBreakingSpace;"/>
  <xsl:output-character character="&#x2262;" string="&amp;NotCongruent;"/>
  <xsl:output-character character="&#x2226;" string="&amp;NotDoubleVerticalBar;"/>
  <xsl:output-character character="&#x2209;" string="&amp;NotElement;"/>
  <xsl:output-character character="&#x2260;" string="&amp;NotEqual;"/>
  <!--U02242-00338 NotEqualTilde-->
  <xsl:output-character character="&#x2204;" string="&amp;NotExists;"/>
  <xsl:output-character character="&#x226f;" string="&amp;NotGreater;"/>
  <xsl:output-character character="&#x2271;" string="&amp;NotGreaterEqual;"/>
  <!--U02267-00338 NotGreaterFullEqual-->
  <!--U0226B-00338 NotGreaterGreater-->
  <xsl:output-character character="&#x2279;" string="&amp;NotGreaterLess;"/>
  <!--U02A7E-00338 NotGreaterSlantEqual-->
  <xsl:output-character character="&#x2275;" string="&amp;NotGreaterTilde;"/>
  <!--U0224E-00338 NotHumpDownHump-->
  <xsl:output-character character="&#x22ea;" string="&amp;NotLeftTriangle;"/>
  <xsl:output-character character="&#x22ec;" string="&amp;NotLeftTriangleEqual;"/>
  <xsl:output-character character="&#x226e;" string="&amp;NotLess;"/>
  <xsl:output-character character="&#x2270;" string="&amp;NotLessEqual;"/>
  <xsl:output-character character="&#x2278;" string="&amp;NotLessGreater;"/>
  <!--U0226A-00338 NotLessLess-->
  <!--U02A7D-00338 NotLessSlantEqual-->
  <xsl:output-character character="&#x2274;" string="&amp;NotLessTilde;"/>
  <xsl:output-character character="&#x2280;" string="&amp;NotPrecedes;"/>
  <!--U02AAF-00338 NotPrecedesEqual-->
  <xsl:output-character character="&#x22e0;" string="&amp;NotPrecedesSlantEqual;"/>
  <xsl:output-character character="&#x220c;" string="&amp;NotReverseElement;"/>
  <xsl:output-character character="&#x22eb;" string="&amp;NotRightTriangle;"/>
  <xsl:output-character character="&#x22ed;" string="&amp;NotRightTriangleEqual;"/>
  <xsl:output-character character="&#x22e2;" string="&amp;NotSquareSubsetEqual;"/>
  <xsl:output-character character="&#x22e3;" string="&amp;NotSquareSupersetEqual;"/>
  <!--U02282-020D2 NotSubset-->
  <xsl:output-character character="&#x2288;" string="&amp;NotSubsetEqual;"/>
  <xsl:output-character character="&#x2281;" string="&amp;NotSucceeds;"/>
  <!--U02AB0-00338 NotSucceedsEqual-->
  <xsl:output-character character="&#x22e1;" string="&amp;NotSucceedsSlantEqual;"/>
  <!--U02283-020D2 NotSuperset-->
  <xsl:output-character character="&#x2289;" string="&amp;NotSupersetEqual;"/>
  <xsl:output-character character="&#x2241;" string="&amp;NotTilde;"/>
  <xsl:output-character character="&#x2244;" string="&amp;NotTildeEqual;"/>
  <xsl:output-character character="&#x2247;" string="&amp;NotTildeFullEqual;"/>
  <xsl:output-character character="&#x2249;" string="&amp;NotTildeTilde;"/>
  <xsl:output-character character="&#x2224;" string="&amp;NotVerticalBar;"/>
  <xsl:output-character character="&#x2226;" string="&amp;nparallel;"/>
  <xsl:output-character character="&#x2280;" string="&amp;nprec;"/>
  <!--U02AAF-00338 npreceq-->
  <xsl:output-character character="&#x219b;" string="&amp;nrightarrow;"/>
  <xsl:output-character character="&#x21cf;" string="&amp;nRightarrow;"/>
  <xsl:output-character character="&#x2224;" string="&amp;nshortmid;"/>
  <xsl:output-character character="&#x2226;" string="&amp;nshortparallel;"/>
  <xsl:output-character character="&#x2244;" string="&amp;nsimeq;"/>
  <!--U02282-020D2 nsubset-->
  <xsl:output-character character="&#x2288;" string="&amp;nsubseteq;"/>
  <!--U02AC5-00338 nsubseteqq-->
  <xsl:output-character character="&#x2281;" string="&amp;nsucc;"/>
  <!--U02AB0-00338 nsucceq-->
  <!--U02283-020D2 nsupset-->
  <xsl:output-character character="&#x2289;" string="&amp;nsupseteq;"/>
  <!--U02AC6-00338 nsupseteqq-->
  <xsl:output-character character="&#x22ea;" string="&amp;ntriangleleft;"/>
  <xsl:output-character character="&#x22ec;" string="&amp;ntrianglelefteq;"/>
  <xsl:output-character character="&#x22eb;" string="&amp;ntriangleright;"/>
  <xsl:output-character character="&#x22ed;" string="&amp;ntrianglerighteq;"/>
  <xsl:output-character character="&#x2196;" string="&amp;nwarrow;"/>
  <xsl:output-character character="&#x222e;" string="&amp;oint;"/>
  <xsl:output-character character="&#x201c;" string="&amp;OpenCurlyDoubleQuote;"/>
  <xsl:output-character character="&#x2018;" string="&amp;OpenCurlyQuote;"/>
  <xsl:output-character character="&#x2134;" string="&amp;orderof;"/>
  <xsl:output-character character="&#x2225;" string="&amp;parallel;"/>
  <xsl:output-character character="&#x2202;" string="&amp;PartialD;"/>
  <xsl:output-character character="&#x22d4;" string="&amp;pitchfork;"/>
  <xsl:output-character character="&#xb1;" string="&amp;PlusMinus;"/>
  <xsl:output-character character="&#xb1;" string="&amp;pm;"/>
  <xsl:output-character character="&#x210c;" string="&amp;Poincareplane;"/>
  <xsl:output-character character="&#x227a;" string="&amp;prec;"/>
  <xsl:output-character character="&#x2ab7;" string="&amp;precapprox;"/>
  <xsl:output-character character="&#x227c;" string="&amp;preccurlyeq;"/>
  <xsl:output-character character="&#x227a;" string="&amp;Precedes;"/>
  <xsl:output-character character="&#x2aaf;" string="&amp;PrecedesEqual;"/>
  <xsl:output-character character="&#x227c;" string="&amp;PrecedesSlantEqual;"/>
  <xsl:output-character character="&#x227e;" string="&amp;PrecedesTilde;"/>
  <xsl:output-character character="&#x2aaf;" string="&amp;preceq;"/>
  <xsl:output-character character="&#x2ab9;" string="&amp;precnapprox;"/>
  <xsl:output-character character="&#x2ab5;" string="&amp;precneqq;"/>
  <xsl:output-character character="&#x22e8;" string="&amp;precnsim;"/>
  <xsl:output-character character="&#x227e;" string="&amp;precsim;"/>
  <xsl:output-character character="&#x2119;" string="&amp;primes;"/>
  <xsl:output-character character="&#x2237;" string="&amp;Proportion;"/>
  <xsl:output-character character="&#x221d;" string="&amp;Proportional;"/>
  <xsl:output-character character="&#x221d;" string="&amp;propto;"/>
  <xsl:output-character character="&#x210d;" string="&amp;quaternions;"/>
  <xsl:output-character character="&#x225f;" string="&amp;questeq;"/>
  <xsl:output-character character="&#x27e9;" string="&amp;rangle;"/>
  <xsl:output-character character="&#x211a;" string="&amp;rationals;"/>
  <!--U0007D rbrace-->
  <!--U0005D rbrack-->
  <xsl:output-character character="&#x211c;" string="&amp;Re;"/>
  <xsl:output-character character="&#x211b;" string="&amp;realine;"/>
  <xsl:output-character character="&#x211c;" string="&amp;realpart;"/>
  <xsl:output-character character="&#x211d;" string="&amp;reals;"/>
  <xsl:output-character character="&#x220b;" string="&amp;ReverseElement;"/>
  <xsl:output-character character="&#x21cb;" string="&amp;ReverseEquilibrium;"/>
  <xsl:output-character character="&#x296f;" string="&amp;ReverseUpEquilibrium;"/>
  <xsl:output-character character="&#x27e9;" string="&amp;RightAngleBracket;"/>
  <xsl:output-character character="&#x2192;" string="&amp;rightarrow;"/>
  <xsl:output-character character="&#x21d2;" string="&amp;Rightarrow;"/>
  <xsl:output-character character="&#x2192;" string="&amp;RightArrow;"/>
  <xsl:output-character character="&#x21e5;" string="&amp;RightArrowBar;"/>
  <xsl:output-character character="&#x21c4;" string="&amp;RightArrowLeftArrow;"/>
  <xsl:output-character character="&#x21a3;" string="&amp;rightarrowtail;"/>
  <xsl:output-character character="&#x2309;" string="&amp;RightCeiling;"/>
  <xsl:output-character character="&#x27e7;" string="&amp;RightDoubleBracket;"/>
  <xsl:output-character character="&#x21c2;" string="&amp;RightDownVector;"/>
  <xsl:output-character character="&#x230b;" string="&amp;RightFloor;"/>
  <xsl:output-character character="&#x21c1;" string="&amp;rightharpoondown;"/>
  <xsl:output-character character="&#x21c0;" string="&amp;rightharpoonup;"/>
  <xsl:output-character character="&#x21c4;" string="&amp;rightleftarrows;"/>
  <xsl:output-character character="&#x21cc;" string="&amp;rightleftharpoons;"/>
  <xsl:output-character character="&#x21c9;" string="&amp;rightrightarrows;"/>
  <xsl:output-character character="&#x219d;" string="&amp;rightsquigarrow;"/>
  <xsl:output-character character="&#x22a2;" string="&amp;RightTee;"/>
  <xsl:output-character character="&#x21a6;" string="&amp;RightTeeArrow;"/>
  <xsl:output-character character="&#x22cc;" string="&amp;rightthreetimes;"/>
  <xsl:output-character character="&#x22b3;" string="&amp;RightTriangle;"/>
  <xsl:output-character character="&#x22b5;" string="&amp;RightTriangleEqual;"/>
  <xsl:output-character character="&#x21be;" string="&amp;RightUpVector;"/>
  <xsl:output-character character="&#x21c0;" string="&amp;RightVector;"/>
  <xsl:output-character character="&#x2253;" string="&amp;risingdotseq;"/>
  <xsl:output-character character="&#x23b1;" string="&amp;rmoustache;"/>
  <xsl:output-character character="&#x21db;" string="&amp;Rrightarrow;"/>
  <xsl:output-character character="&#x21b1;" string="&amp;Rsh;"/>
  <xsl:output-character character="&#x2198;" string="&amp;searrow;"/>
  <xsl:output-character character="&#x2216;" string="&amp;setminus;"/>
  <xsl:output-character character="&#x2193;" string="&amp;ShortDownArrow;"/>
  <xsl:output-character character="&#x2190;" string="&amp;ShortLeftArrow;"/>
  <xsl:output-character character="&#x2223;" string="&amp;shortmid;"/>
  <xsl:output-character character="&#x2225;" string="&amp;shortparallel;"/>
  <xsl:output-character character="&#x2192;" string="&amp;ShortRightArrow;"/>
  <xsl:output-character character="&#x2191;" string="&amp;ShortUpArrow;"/>
  <xsl:output-character character="&#x2243;" string="&amp;simeq;"/>
  <xsl:output-character character="&#x2218;" string="&amp;SmallCircle;"/>
  <xsl:output-character character="&#x2216;" string="&amp;smallsetminus;"/>
  <xsl:output-character character="&#x2660;" string="&amp;spadesuit;"/>
  <xsl:output-character character="&#x221a;" string="&amp;Sqrt;"/>
  <xsl:output-character character="&#x228f;" string="&amp;sqsubset;"/>
  <xsl:output-character character="&#x2291;" string="&amp;sqsubseteq;"/>
  <xsl:output-character character="&#x2290;" string="&amp;sqsupset;"/>
  <xsl:output-character character="&#x2292;" string="&amp;sqsupseteq;"/>
  <xsl:output-character character="&#x25a1;" string="&amp;Square;"/>
  <xsl:output-character character="&#x2293;" string="&amp;SquareIntersection;"/>
  <xsl:output-character character="&#x228f;" string="&amp;SquareSubset;"/>
  <xsl:output-character character="&#x2291;" string="&amp;SquareSubsetEqual;"/>
  <xsl:output-character character="&#x2290;" string="&amp;SquareSuperset;"/>
  <xsl:output-character character="&#x2292;" string="&amp;SquareSupersetEqual;"/>
  <xsl:output-character character="&#x2294;" string="&amp;SquareUnion;"/>
  <xsl:output-character character="&#x22c6;" string="&amp;Star;"/>
  <xsl:output-character character="&#x3f5;" string="&amp;straightepsilon;"/>
  <xsl:output-character character="&#x3d5;" string="&amp;straightphi;"/>
  <xsl:output-character character="&#x2282;" string="&amp;subset;"/>
  <xsl:output-character character="&#x22d0;" string="&amp;Subset;"/>
  <xsl:output-character character="&#x2286;" string="&amp;subseteq;"/>
  <xsl:output-character character="&#x2ac5;" string="&amp;subseteqq;"/>
  <xsl:output-character character="&#x2286;" string="&amp;SubsetEqual;"/>
  <xsl:output-character character="&#x228a;" string="&amp;subsetneq;"/>
  <xsl:output-character character="&#x2acb;" string="&amp;subsetneqq;"/>
  <xsl:output-character character="&#x227b;" string="&amp;succ;"/>
  <xsl:output-character character="&#x2ab8;" string="&amp;succapprox;"/>
  <xsl:output-character character="&#x227d;" string="&amp;succcurlyeq;"/>
  <xsl:output-character character="&#x227b;" string="&amp;Succeeds;"/>
  <xsl:output-character character="&#x2ab0;" string="&amp;SucceedsEqual;"/>
  <xsl:output-character character="&#x227d;" string="&amp;SucceedsSlantEqual;"/>
  <xsl:output-character character="&#x227f;" string="&amp;SucceedsTilde;"/>
  <xsl:output-character character="&#x2ab0;" string="&amp;succeq;"/>
  <xsl:output-character character="&#x2aba;" string="&amp;succnapprox;"/>
  <xsl:output-character character="&#x2ab6;" string="&amp;succneqq;"/>
  <xsl:output-character character="&#x22e9;" string="&amp;succnsim;"/>
  <xsl:output-character character="&#x227f;" string="&amp;succsim;"/>
  <xsl:output-character character="&#x220b;" string="&amp;SuchThat;"/>
  <xsl:output-character character="&#x2211;" string="&amp;Sum;"/>
  <xsl:output-character character="&#x2283;" string="&amp;Superset;"/>
  <xsl:output-character character="&#x2287;" string="&amp;SupersetEqual;"/>
  <xsl:output-character character="&#x2283;" string="&amp;supset;"/>
  <xsl:output-character character="&#x22d1;" string="&amp;Supset;"/>
  <xsl:output-character character="&#x2287;" string="&amp;supseteq;"/>
  <xsl:output-character character="&#x2ac6;" string="&amp;supseteqq;"/>
  <xsl:output-character character="&#x228b;" string="&amp;supsetneq;"/>
  <xsl:output-character character="&#x2acc;" string="&amp;supsetneqq;"/>
  <xsl:output-character character="&#x2199;" string="&amp;swarrow;"/>
  <xsl:output-character character="&#x2234;" string="&amp;therefore;"/>
  <xsl:output-character character="&#x2234;" string="&amp;Therefore;"/>
  <xsl:output-character character="&#x2248;" string="&amp;thickapprox;"/>
  <xsl:output-character character="&#x223c;" string="&amp;thicksim;"/>
  <xsl:output-character character="&#x2009;" string="&amp;ThinSpace;"/>
  <xsl:output-character character="&#x223c;" string="&amp;Tilde;"/>
  <xsl:output-character character="&#x2243;" string="&amp;TildeEqual;"/>
  <xsl:output-character character="&#x2245;" string="&amp;TildeFullEqual;"/>
  <xsl:output-character character="&#x2248;" string="&amp;TildeTilde;"/>
  <xsl:output-character character="&#x2928;" string="&amp;toea;"/>
  <xsl:output-character character="&#x2929;" string="&amp;tosa;"/>
  <xsl:output-character character="&#x25b5;" string="&amp;triangle;"/>
  <xsl:output-character character="&#x25bf;" string="&amp;triangledown;"/>
  <xsl:output-character character="&#x25c3;" string="&amp;triangleleft;"/>
  <xsl:output-character character="&#x22b4;" string="&amp;trianglelefteq;"/>
  <xsl:output-character character="&#x225c;" string="&amp;triangleq;"/>
  <xsl:output-character character="&#x25b9;" string="&amp;triangleright;"/>
  <xsl:output-character character="&#x22b5;" string="&amp;trianglerighteq;"/>
  <xsl:output-character character="&#x20db;" string="&amp;TripleDot;"/>
  <xsl:output-character character="&#x219e;" string="&amp;twoheadleftarrow;"/>
  <xsl:output-character character="&#x21a0;" string="&amp;twoheadrightarrow;"/>
  <xsl:output-character character="&#x231c;" string="&amp;ulcorner;"/>
  <xsl:output-character character="&#x22c3;" string="&amp;Union;"/>
  <xsl:output-character character="&#x228e;" string="&amp;UnionPlus;"/>
  <xsl:output-character character="&#x2191;" string="&amp;uparrow;"/>
  <xsl:output-character character="&#x21d1;" string="&amp;Uparrow;"/>
  <xsl:output-character character="&#x2191;" string="&amp;UpArrow;"/>
  <xsl:output-character character="&#x21c5;" string="&amp;UpArrowDownArrow;"/>
  <xsl:output-character character="&#x2195;" string="&amp;updownarrow;"/>
  <xsl:output-character character="&#x21d5;" string="&amp;Updownarrow;"/>
  <xsl:output-character character="&#x2195;" string="&amp;UpDownArrow;"/>
  <xsl:output-character character="&#x296e;" string="&amp;UpEquilibrium;"/>
  <xsl:output-character character="&#x21bf;" string="&amp;upharpoonleft;"/>
  <xsl:output-character character="&#x21be;" string="&amp;upharpoonright;"/>
  <xsl:output-character character="&#x2196;" string="&amp;UpperLeftArrow;"/>
  <xsl:output-character character="&#x2197;" string="&amp;UpperRightArrow;"/>
  <xsl:output-character character="&#x3c5;" string="&amp;upsilon;"/>
  <xsl:output-character character="&#x22a5;" string="&amp;UpTee;"/>
  <xsl:output-character character="&#x21a5;" string="&amp;UpTeeArrow;"/>
  <xsl:output-character character="&#x21c8;" string="&amp;upuparrows;"/>
  <xsl:output-character character="&#x231d;" string="&amp;urcorner;"/>
  <xsl:output-character character="&#x3f5;" string="&amp;varepsilon;"/>
  <xsl:output-character character="&#x3f0;" string="&amp;varkappa;"/>
  <xsl:output-character character="&#x2205;" string="&amp;varnothing;"/>
  <xsl:output-character character="&#x3d5;" string="&amp;varphi;"/>
  <xsl:output-character character="&#x3d6;" string="&amp;varpi;"/>
  <xsl:output-character character="&#x221d;" string="&amp;varpropto;"/>
  <xsl:output-character character="&#x3f1;" string="&amp;varrho;"/>
  <xsl:output-character character="&#x3c2;" string="&amp;varsigma;"/>
  <!--U0228A-0FE00 varsubsetneq-->
  <!--U02ACB-0FE00 varsubsetneqq-->
  <!--U0228B-0FE00 varsupsetneq-->
  <!--U02ACC-0FE00 varsupsetneqq-->
  <xsl:output-character character="&#x3d1;" string="&amp;vartheta;"/>
  <xsl:output-character character="&#x22b2;" string="&amp;vartriangleleft;"/>
  <xsl:output-character character="&#x22b3;" string="&amp;vartriangleright;"/>
  <xsl:output-character character="&#x2228;" string="&amp;vee;"/>
  <xsl:output-character character="&#x22c1;" string="&amp;Vee;"/>
  <!--U0007C vert-->
  <xsl:output-character character="&#x2016;" string="&amp;Vert;"/>
  <xsl:output-character character="&#x2223;" string="&amp;VerticalBar;"/>
  <xsl:output-character character="&#x2240;" string="&amp;VerticalTilde;"/>
  <xsl:output-character character="&#x200a;" string="&amp;VeryThinSpace;"/>
  <xsl:output-character character="&#x2227;" string="&amp;wedge;"/>
  <xsl:output-character character="&#x22c0;" string="&amp;Wedge;"/>
  <xsl:output-character character="&#x2118;" string="&amp;wp;"/>
  <xsl:output-character character="&#x2240;" string="&amp;wr;"/>
  <xsl:output-character character="&#x2128;" string="&amp;zeetrf;"/>
</xsl:character-map>

</xsl:stylesheet>
